# netlifycms.org/
backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog" #where the images are located
public_folder: "/assets/blog" #where the images are saved (ditch the public part)
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}--{{month}}--{{day}}-{{slug}}" #Essentially the title of the post
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
